[runtime]
env = { NODE_VERSION = "20.9.0" }

[scripts]
dev = "next dev"
build = "next build"
start = "next start"
lint = "next lint"

[install]
exact = true

[install.scopes]
next = "workspace:*"

[test]
coverage = true